name: Hourly Bot

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install requests pandas numpy

      - run: |
        pwd
          ls -R
          python src/fetch_fx.py
          python src/fetch_weather.py
          python src/indicators.py
          python src/trading_engine.py
          python src/report.py

      - run: |
          git config user.name "bot"
          git config user.email "bot@github"
          git add .
          git commit -m "Hourly update" || echo "No changes"
          git push

